spring.application.name=pharmacyservice

server.port=8088

#logging.level.root=DEBUG

app.cors.allowed-origin-patterns=http://localhost:3000,http://127.0.0.1:3000

spring.datasource.url=${PHARMACY_DB_URL:jdbc:oracle:thin:@seoulit.pe.kr:1521/FREEPDB1}
spring.datasource.username=${PHARMACY_DB_USERNAME:pharmacy}
spring.datasource.password=${PHARMACY_DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=PHARMACY
spring.jpa.open-in-view=false

public-data.medication.base-url=${PUBLIC_DATA_MEDICATION_BASE_URL:https://apis.data.go.kr/1471000/MdcinGrnIdntfcInfoService03/getMdcinGrnIdntfcInfoList03}
public-data.medication.service-key=${PUBLIC_DATA_MEDICATION_SERVICE_KEY:bf3a67e34427e8e3bd9aa909b0458add47a81d1561e327660752e2e767a2713b}
