spring.application.name=pharmacyservice

spring.datasource.url=${PHARMACY_DB_URL}
spring.datasource.username=${PHARMACY_DB_USERNAME}
spring.datasource.password=${PHARMACY_DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=PHARMACY
spring.jpa.open-in-view=false

- 