-- PHARMACY 스키마 테이블/컬럼 주석 (짧은 라벨)

COMMENT ON TABLE PHARMACY.MEDICATION IS '약품';
COMMENT ON COLUMN PHARMACY.MEDICATION.MEDICATION_ID IS '약품ID';
COMMENT ON COLUMN PHARMACY.MEDICATION.MEDICATION_NAME IS '제품명';
COMMENT ON COLUMN PHARMACY.MEDICATION.ITEM_SEQ IS '품목기준코드';
COMMENT ON COLUMN PHARMACY.MEDICATION.ITEM_ENG_NAME IS '영문명';
COMMENT ON COLUMN PHARMACY.MEDICATION.ENTP_NAME IS '업체명';
COMMENT ON COLUMN PHARMACY.MEDICATION.ETC_OTC_NAME IS '전문/일반구분';
COMMENT ON COLUMN PHARMACY.MEDICATION.CLASS_NO IS '분류번호';
COMMENT ON COLUMN PHARMACY.MEDICATION.CLASS_NAME IS '분류명';
COMMENT ON COLUMN PHARMACY.MEDICATION.FORM_CODE_NAME IS '제형';
COMMENT ON COLUMN PHARMACY.MEDICATION.CHART IS '성상';
COMMENT ON COLUMN PHARMACY.MEDICATION.ITEM_PERMIT_DATE IS '허가일자';
COMMENT ON COLUMN PHARMACY.MEDICATION.EDI_CODE IS 'EDI코드';
COMMENT ON COLUMN PHARMACY.MEDICATION.STD_CD IS '표준코드';
COMMENT ON COLUMN PHARMACY.MEDICATION.CREATED_AT IS '등록일시';
COMMENT ON COLUMN PHARMACY.MEDICATION.UPDATED_AT IS '수정일시';

COMMENT ON TABLE PHARMACY.MEDICATION_LOT IS '약품 로트';
COMMENT ON COLUMN PHARMACY.MEDICATION_LOT.MEDICATION_LOT_ID IS '로트ID';
COMMENT ON COLUMN PHARMACY.MEDICATION_LOT.MEDICATION_ID IS '약품ID';
COMMENT ON COLUMN PHARMACY.MEDICATION_LOT.LOT_NO IS '로트번호';
COMMENT ON COLUMN PHARMACY.MEDICATION_LOT.EXPIRATION_DT IS '유효기간';
COMMENT ON COLUMN PHARMACY.MEDICATION_LOT.MANUFACTURE_DT IS '제조일자';
COMMENT ON COLUMN PHARMACY.MEDICATION_LOT.UNIT_CD IS '단위코드';

COMMENT ON TABLE PHARMACY.MEDICATION_STOCK IS '약품 재고';
COMMENT ON COLUMN PHARMACY.MEDICATION_STOCK.MEDICATION_STOCK_ID IS '재고ID';
COMMENT ON COLUMN PHARMACY.MEDICATION_STOCK.MEDICATION_LOT_ID IS '로트ID';
COMMENT ON COLUMN PHARMACY.MEDICATION_STOCK.STORAGE_LOCATION_ID IS '보관위치';
COMMENT ON COLUMN PHARMACY.MEDICATION_STOCK.CURRENT_QTY IS '현재수량';
COMMENT ON COLUMN PHARMACY.MEDICATION_STOCK.LAST_MOVEMENT_AT IS '최종변동일시';

COMMENT ON TABLE PHARMACY.MEDICATION_RECEIPT IS '약품 입고';
COMMENT ON COLUMN PHARMACY.MEDICATION_RECEIPT.MEDICATION_RECEIPT_ID IS '입고ID';
COMMENT ON COLUMN PHARMACY.MEDICATION_RECEIPT.SUPPLIER_ID IS '공급업체';
COMMENT ON COLUMN PHARMACY.MEDICATION_RECEIPT.STORAGE_LOCATION_ID IS '보관위치';
COMMENT ON COLUMN PHARMACY.MEDICATION_RECEIPT.RECEIPT_DT IS '입고일자';
COMMENT ON COLUMN PHARMACY.MEDICATION_RECEIPT.RECEIVED_BY_ID IS '담당자';

COMMENT ON TABLE PHARMACY.MEDICATION_RECEIPT_ITEM IS '입고 항목';
COMMENT ON COLUMN PHARMACY.MEDICATION_RECEIPT_ITEM.MEDICATION_RECEIPT_ITEM_ID IS '입고항목ID';
COMMENT ON COLUMN PHARMACY.MEDICATION_RECEIPT_ITEM.MEDICATION_RECEIPT_ID IS '입고ID';
COMMENT ON COLUMN PHARMACY.MEDICATION_RECEIPT_ITEM.MEDICATION_LOT_ID IS '로트ID';
COMMENT ON COLUMN PHARMACY.MEDICATION_RECEIPT_ITEM.RECEIPT_QTY IS '입고수량';
COMMENT ON COLUMN PHARMACY.MEDICATION_RECEIPT_ITEM.UNIT_PRICE IS '단가';

COMMENT ON TABLE PHARMACY.INVENTORY_MOVEMENT IS '재고 이력';
COMMENT ON COLUMN PHARMACY.INVENTORY_MOVEMENT.INVENTORY_MOVEMENT_ID IS '이력ID';
COMMENT ON COLUMN PHARMACY.INVENTORY_MOVEMENT.MEDICATION_STOCK_ID IS '재고ID';
COMMENT ON COLUMN PHARMACY.INVENTORY_MOVEMENT.STOCK_TX_TYPE_CD IS '입출고유형';
COMMENT ON COLUMN PHARMACY.INVENTORY_MOVEMENT.MOVEMENT_QTY IS '변동수량';
COMMENT ON COLUMN PHARMACY.INVENTORY_MOVEMENT.BEFORE_QTY IS '변동전수량';
COMMENT ON COLUMN PHARMACY.INVENTORY_MOVEMENT.AFTER_QTY IS '변동후수량';
COMMENT ON COLUMN PHARMACY.INVENTORY_MOVEMENT.SOURCE_FORM_ID IS '근거전표ID';
COMMENT ON COLUMN PHARMACY.INVENTORY_MOVEMENT.SOURCE_FORM_TYPE_CD IS '근거전표유형';
COMMENT ON COLUMN PHARMACY.INVENTORY_MOVEMENT.MOVEMENT_AT IS '변동일시';
COMMENT ON COLUMN PHARMACY.INVENTORY_MOVEMENT.MOVED_BY_ID IS '처리자';

COMMENT ON TABLE PHARMACY.PRESCRIPTION_LINK IS '처방전';
COMMENT ON COLUMN PHARMACY.PRESCRIPTION_LINK.PRESCRIPTION_LINK_ID IS '처방전링크ID';
COMMENT ON COLUMN PHARMACY.PRESCRIPTION_LINK.PRESCRIPTION_ID IS '처방전ID';
COMMENT ON COLUMN PHARMACY.PRESCRIPTION_LINK.PATIENT_ID IS '환자ID';
COMMENT ON COLUMN PHARMACY.PRESCRIPTION_LINK.PHYSICIAN_ID IS '의사ID';
COMMENT ON COLUMN PHARMACY.PRESCRIPTION_LINK.DEPARTMENT_ID IS '진료과ID';
COMMENT ON COLUMN PHARMACY.PRESCRIPTION_LINK.CREATED_AT IS '등록일시';

COMMENT ON TABLE PHARMACY.PRESCRIPTION_ITEM_LINK IS '처방 항목';
COMMENT ON COLUMN PHARMACY.PRESCRIPTION_ITEM_LINK.PRESCRIPTION_ITEM_LINK_ID IS '처방항목ID';
COMMENT ON COLUMN PHARMACY.PRESCRIPTION_ITEM_LINK.PRESCRIPTION_LINK_ID IS '처방전ID';
COMMENT ON COLUMN PHARMACY.PRESCRIPTION_ITEM_LINK.MEDICATION_ID IS '약품ID';
COMMENT ON COLUMN PHARMACY.PRESCRIPTION_ITEM_LINK.DOSAGE_QTY IS '용량';
COMMENT ON COLUMN PHARMACY.PRESCRIPTION_ITEM_LINK.DOSAGE_FORM_CD IS '제형코드';
COMMENT ON COLUMN PHARMACY.PRESCRIPTION_ITEM_LINK.FREQUENCY IS '투여횟수';
COMMENT ON COLUMN PHARMACY.PRESCRIPTION_ITEM_LINK.DURATION_DAYS IS '투약일수';
COMMENT ON COLUMN PHARMACY.PRESCRIPTION_ITEM_LINK.DETAIL_INFO IS '복약안내';

COMMIT;
